#!/bin/bash

# 切换到脚本所在目录
cd "$(dirname "${BASH_SOURCE[0]}")"

# 保存脚本所在目录的路径
SCRIPT_DIR="/easytools"

CONFIG_SCRIPT_PATH="$SCRIPT_DIR/config.sh"
INSTALL_SCRIPT_PATH="$SCRIPT_DIR/install.sh"
MENU_SCRIPT_PATH="$SCRIPT_DIR/menu.sh"
TEMPLATE_SCRIPT_PATH="$SCRIPT_DIR/template.sh"
UNINSTALL_SCRIPT_PATH="$SCRIPT_DIR/uninstall.sh"
UPDATE_SCRIPT_PATH="$SCRIPT_DIR/update.sh"
DOCKER_LNMP_MENU_SCRIPT_PATH="$SCRIPT_DIR/docker-lnmp/docker_lnmp_menu.sh"
INSTALL_DOCKER_LNMP_SCRIPT_PATH="$SCRIPT_DIR/docker-lnmp/ubuntu-debian/arm64/install_docker_lnmp.sh"
SSL_MENU_SCRIPT_PATH="$SCRIPT_DIR/ssl/ssl_menu.sh"
CENTOS_ACME_SCRIPT_PATH="$SCRIPT_DIR/ssl/centos/centos_acme.sh"
UBUNTU_ACME_SCRIPT_PATH="$SCRIPT_DIR/ssl/ubuntu/ubuntu_acme.sh"
WARP_MENU_SCRIPT_PATH="$SCRIPT_DIR/warp/warp_menu.sh"
WEBSITE_MENU_SCRIPT_PATH="$SCRIPT_DIR/website/website_menu.sh"
INSTALL_V2BOARD_SCRIPT_PATH="$SCRIPT_DIR/website/v2board/install_v2board.sh"
UPDATA_V2BOARD_SCRIPT_PATH="$SCRIPT_DIR/website/v2board/updata_v2board.sh"

# 其他配置...

# 定义路径
echo "CONFIG_SCRIPT_PATH: $CONFIG_SCRIPT_PATH"
echo "INSTALL_SCRIPT_PATH: $INSTALL_SCRIPT_PATH"
echo "MENU_SCRIPT_PATH: $MENU_SCRIPT_PATH"
echo "TEMPLATE_SCRIPT_PATH: $TEMPLATE_SCRIPT_PATH"
echo "UNINSTALL_SCRIPT_PATH: $UNINSTALL_SCRIPT_PATH"
echo "UPDATE_SCRIPT_PATH: $UPDATE_SCRIPT_PATH"
echo "DOCKER_LNMP_MENU_SCRIPT_PATH: $DOCKER_LNMP_MENU_SCRIPT_PATH"
echo "INSTALL_DOCKER_LNMP_SCRIPT_PATH: $INSTALL_DOCKER_LNMP_SCRIPT_PATH"
echo "SSL_MENU_SCRIPT_PATH: $SSL_MENU_SCRIPT_PATH"
echo "CENTOS_ACME_SCRIPT_PATH: $CENTOS_ACME_SCRIPT_PATH"
echo "UBUNTU_ACME_SCRIPT_PATH: $UBUNTU_ACME_SCRIPT_PATH"
echo "WARP_MENU_SCRIPT_PATH: $WARP_MENU_SCRIPT_PATH"
echo "WEBSITE_MENU_SCRIPT_PATH: $WEBSITE_MENU_SCRIPT_PATH"
echo "INSTALL_V2BOARD_SCRIPT_PATH: $INSTALL_V2BOARD_SCRIPT_PATH"
echo "UPDATA_V2BOARD_SCRIPT_PATH: $UPDATA_V2BOARD_SCRIPT_PATH"
