#!/bin/bash

# enter script pwd
cd "$(dirname "${BASH_SOURCE[0]}")"

# script working path
SCRIPT_DIR="/easytools"

ACME_SCRIPT_PATH="$SCRIPT_DIR/acme/acme.sh"
ACME_CENTOS_SCRIPT_PATH="$SCRIPT_DIR/acme/acme_centos.sh"
ACME_UBUNTU_DEBIAN_SCRIPT_PATH="$SCRIPT_DIR/acme/acme_ubuntu_debian.sh"
CONFIG_SCRIPT_PATH="$SCRIPT_DIR/config.sh"
INSTALL_SCRIPT_PATH="$SCRIPT_DIR/install.sh"
MENU_SCRIPT_PATH="$SCRIPT_DIR/menu.sh"
TEMPLATE_SCRIPT_PATH="$SCRIPT_DIR/template.sh"
UNINSTALL_SCRIPT_PATH="$SCRIPT_DIR/uninstall.sh"
UPDATE_SCRIPT_PATH="$SCRIPT_DIR/update.sh"
WARP_MENU_SCRIPT_PATH="$SCRIPT_DIR/warp/warp_menu.sh"

# other config...

# # dev debug
# echo "ACME_SCRIPT_PATH: $ACME_SCRIPT_PATH"
# echo "ACME_CENTOS_SCRIPT_PATH: $ACME_CENTOS_SCRIPT_PATH"
# echo "ACME_UBUNTU_DEBIAN_SCRIPT_PATH: $ACME_UBUNTU_DEBIAN_SCRIPT_PATH"
# echo "CONFIG_SCRIPT_PATH: $CONFIG_SCRIPT_PATH"
# echo "INSTALL_SCRIPT_PATH: $INSTALL_SCRIPT_PATH"
# echo "MENU_SCRIPT_PATH: $MENU_SCRIPT_PATH"
# echo "TEMPLATE_SCRIPT_PATH: $TEMPLATE_SCRIPT_PATH"
# echo "UNINSTALL_SCRIPT_PATH: $UNINSTALL_SCRIPT_PATH"
# echo "UPDATE_SCRIPT_PATH: $UPDATE_SCRIPT_PATH"
# echo "WARP_MENU_SCRIPT_PATH: $WARP_MENU_SCRIPT_PATH"
