Log:
  Level: warning # 日志级别：无、错误、警告、信息、调试 
  AccessPath: # /etc/XrayR/访问日志
  ErrorPath: # /etc/XrayR/错误日志
DnsConfigPath: # /etc/XrayR/dns.json # dns配置路径，查看帮助 https://xtls.github.io/config/dns.html 
RouteConfigPath: # /etc/XrayR/route.json # 路由配置的路径,查看帮助 check https://xtls.github.io/config/routing.html
InboundConfigPath: # /etc/XrayR/custom_inbound.json # 自定义入站配置的路径， 查看帮助 https://xtls.github.io/config/inbound.html
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # 自定义出站配置的路径， 查看帮助 https://xtls.github.io/config/outbound.html
ConnectionConfig:
  Handshake: 4 # 握手时限，第二
  ConnIdle: 10 # 连接空闲时间限制， 第二
  UplinkOnly: 2 # 连接下游关闭时的时间限制， 第二
  DownlinkOnly: 4 # 关闭上行链路后关闭连接时的时间限制， 第二
  BufferSize: 64 # 每个连接的内部缓存大小， kB
Nodes:
  -
    PanelType: "V2board" # 面板类型： SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks            （必须）
    ApiConfig:
      ApiHost: "https://域名.com" # 面板地址                                                                    （必须）
      ApiKey: "123" # 面版ID                                                                                   （必须）
      NodeID: 1 # 节点ID                                                                                       （必须）
      NodeType: Trojan # 节点类型： V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin                              （必须）
      Timeout: 30 # api 请求超时
      EnableVless: false # 为 V2ray 类型启用 Vless
      EnableXTLS: false # 为 V2ray 和 Trojan 启用 XTLS
      SpeedLimit: 0 # Mbps，本地设置将取代远程设置，0 表示禁用
      DeviceLimit: 0 # 本地设置将替换远程设置，0 表示禁用
      RuleListPath: # /etc/XrayR/规则列表 本地规则列表文件的路径
    ControllerConfig: # 控制器配置
      ListenIP: 0.0.0.0 # 您要收听的 IP 地址
      SendIP: 0.0.0.0 # 你要发送包的IP地址
      UpdatePeriodic: 60 # 更新节点信息的时间，多少秒。
      EnableDNS: false # 使用自定义 DNS 配置，请确保您设置好 dns.json
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS 策略
      AutoSpeedLimitConfig: # 自动限速配置
        Limit: 0 # 警告速度。 设置为 0 以禁用自动速度限制 (mbps)
        WarnTimes: 0 # 在（WarnTimes）连续警告后，用户将被限制。 设置为 0 立即惩罚超速用户。
        LimitSpeed: 0 # 受限用户限速（单位：mbps）
        LimitDuration: 0 # 限制持续多少分钟（单位：分钟）
      GlobalDeviceLimitConfig: # 全局设备限制配置
        Enable: false # 启用用户的全局设备限制
        RedisAddr: 127.0.0.1:6379 # redis 服务器地址
        RedisPassword: YOUR PASSWORD # Redis 密码
        RedisDB: 0 # Redis 数据库
        Timeout: 5 # redis 请求超时
        Expiry: 60 # 到期时间（秒）
      EnableFallback: false # 仅支持 Trojan 和 Vless
      FallBackConfigs:  # 支持多个回退
        -
          SNI: # TLS SNI（服务器名称指示），任何为空
          Alpn: # Alpn，为任何空
          Path: # HTTP PATH，任何为空
          Dest: 80 # 必需，后备目的地，了解详情。https://xtls.github.io/config/features/fallback.html 
          ProxyProtocolVer: 0 # 发送 PROXY 协议版本， 0 为禁用
      CertConfig: # 证书配置
        CertMode: dns # 关于如何获取证书的选项：无、文件、http、tls、dns。 选择“无”将强制禁用 tls 配置。
        CertDomain: "域名.com" # 要认证的域                                                                     （必须）
        CertFile: /etc/XrayR/cert/域名.com.cert # 证书模式为文件                                                 （必须）
        KeyFile: /etc/XrayR/cert/域名.com.key # 域名密钥文件                                                    （必须）
        Provider: cloudflare # DNS 证书提供商，在此处获取完整的支持列表: https://go-acme.github.io/lego/dns/        （必须）
        Email: 123@qq.com # 邮箱                                                                                （必须）
        DNSEnv: # DNS 提供商使用的 DNS ENV 选项
          CLOUDFLARE_EMAIL: 123@qq.com # 域名商的用户名 或 邮箱                                                   （必须）
          CLOUDFLARE_API_KEY: 123 # 域名商的 API Key                                                            （必须）
